### PR TITLE
name change because of mismatch

### PR DESCRIPTION
**Pull request by rjdkolb**
I had a name mismatch.
Hope you don't mind Mani, but I changed the container to adoptopenjdk.
This matches in with the second pull request for valhalla.

### CODE REVIEW

**Comment by neomatrix369** [comment]
Name change okay. Had to happen one of these days.

**Comment by neomatrix369** [comment]
@rjdkolb - i haven;t run the script but I trust it works as it is a copy of the previous one with changes in labels and hg url. This strikes me to be duplications between the scripts - would you like to merged these scripts into one - by generifying them and then using CL parameters, environment variables, etc... to run the different types of builds:
openjdk9
jigsaw
valhalla

All of these controlled by one script but invoked with different CL parameters.
*CL = commandline

What do you think ? If you need help feel free to push whatever changes you can do and I'll help fix if any.

**Comment by neomatrix369** [comment]
For the moment lets not worry about cases where this wont work.

Also did you get a chance to look at the Vagrant scripts ? They might need similar amendments but lets finish the Docker one.

**Comment by rjdkolb** [comment]
great. 
Agreed the CL parameters, environment variables is a better idea.
Please close this PR, I'll think about it and submit another early in the week.

**Comment by rjdkolb** [comment]
Oh, I have not looked at the Vagrant scripts.
The docker idea is much better in my opinion.

**Pull request closed without merging**
